name: Test Compiler
on:
  pull_request_review:
    types:
      - submitted
jobs:
  Test-Actions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.x ]
    steps:
      - name: Testing echo
        run: echo "Starting ${{ github.event_name }}"
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm install
      - run: npm run build
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          directory: '.'
          filename: 'release.zip'
          exclusions: '*.git* /*node_modules/* .editorconfig'
      - name: Upload to git
        uses: actions/upload-artifact@v1
        with:
          name: my-artifact
          path: ${{ github.workspace }}/release.zip


