name: Custom Build
on:
  workflow_dispatch:
  push:
    # Pattern matched against refs/tags
    tags:
      - 'release/**'

jobs:
  Test-Actions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.x ]
    steps:
      - name: Testing echo
        run: |
          echo "Starting ${{ github.event_name }}"
          echo "Repo name ${{github.event.repository.name}}"
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm install
      - run: npm run build
      - name: Archive Release
        run: |
          base=$(basename $PWD)
          echo "${{base}}"
          tar_file_name=$base.tar.gz
          touch $tar_file_name
          tar -czf $tar_file_name --exclude=$tar_file_name .
      - name: Upload to git
        uses: actions/upload-artifact@v1
        with:
          name: my-artifact
          path: ${{ github.workspace }}/$tar_file_name.tar.gz


